feat: OAuth2를 이용한 kakao, google 소셜로그인 구현
sonisori/Server pull request #18
Opened 2024-10-29 01:10 UTC by LEE-GYU-BIN

# Pull requests
### 작업한 내용
application properties에 다음 내용을 추가해주세요!
(클라이언트id, secret, jwt-secret 은 따로 공유드리겠습니다)
```java
#registration
spring.security.oauth2.client.registration.google.client-name=google
spring.security.oauth2.client.registration.google.client-id=
spring.security.oauth2.client.registration.google.client-secret=
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.google.scope=profile,email
#Kakao
spring.security.oauth2.client.registration.kakao.client-name=kakao
spring.security.oauth2.client.registration.kakao.client-id=
spring.security.oauth2.client.registration.kakao.client-secret=
spring.security.oauth2.client.registration.kakao.redirect-uri=http://localhost:8080/login/oauth2/code/kakao
spring.security.oauth2.client.registration.kakao.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.kakao.scope=profile_nickname
#provider
spring.security.oauth2.client.provider.kakao.authorization-uri=https://kauth.kakao.com/oauth/authorize
spring.security.oauth2.client.provider.kakao.token-uri=https://kauth.kakao.com/oauth/token
spring.security.oauth2.client.provider.kakao.user-info-uri=https://kapi.kakao.com/v2/user/me
spring.security.oauth2.client.provider.kakao.user-name-attribute=id
#jwt
spring.jwt.secret=

* 리소스 서버에서 제공해주는 유저 정보를 처리하기 위한 CustomOAuth2UserService를 구현하였습니다
   *  KakaoResponse, GoogleResponse 객체를 구현하여 각 서비스에 맞는 처리를 진행하도록 하였습니다.
   *  UserDto 객체와 CustomOAuth2User 객체를 구현하여 리소스 서버를 통해 받은 정보를 UserDto 에 담아 CustomOAuth2User에 담아 provider로 넘기도록 하였습니다.
   
* 로그인이 성공하면 실행될 CustomSuccessHandler 를 구현하였습니다. 
   * 핸들러 내부에서 JWT 발급을 구현하였습니다.
   * 이때 하이퍼링크로 백엔드에 요청하기 때문에 jwt를 발급할때 쿠키에 담아 발급하는 방식으로 진행하였습니다.
   * JWT는 HS256 암호화 알고리즘을 사용하였습니다.
   * JWT 발급에 사용되는 JwtUitl 객체를 구현하였습니다.
   
* 요청에 담겨 날라오는 JWT를 검증하기 위한 JwtFilter 를 구현하였습니다.

### PR Point
-  Kakao Response 부분에서 email을 받는 부분을 null 처리 했습니다. 카카오에서 로그인시 이메일을 받으려면 앱 심사를 받아야 한다고 해서 처리했는데 맞는지 확인해주세요!
- 필요없는 데이터를 처리하는 부분이 없는지, 중요한 데이터 처리를 놓친게 있는지 확인해주세요!

### 📸 스크린샷
- 스크린 샷 혹은 동영상을 첨부해주세요.

| 사진 | 설명 |
| --- | --- |
| | |

### 논의 사항 -- 질문
궁금한 사항이 많아서 질문을 남깁니다

1. 먼저 구현을 다 한뒤에 테스트를 진행하고 싶었는데 부끄럽게도 DB랑 연동하여 테스트하는 방법을 잘 몰라 테스트를 해보지 못했습니다. 이 과정을 고민하며 찾아보다 보니 먼저 기존의 UserEntity 에서 작성했던 내용과 제가 이번에 생성하여 만든 UserDto 가 일치해야 하지 않나 라는 생각이 들었습니다. 맞을까요 ?

2. 전에 jwt refreshtoken 관련하여 올려주신 PR 내용도 반영하지 못한 것 같습니다. Access 토큰 같은 경우 Oauth 설정을 하면 filter에서 자동적으로 처리한다고 알고있습니다. 맞을까요? 그러면 refresh token은 어떻게 처리해야하는지 궁금합니다.

올려주신 강의 참고하여 공부하면서 작성을 해봤는데 부족한 점이 꽤 많은 것 같습니다.. 죄송합니다 피드백 주시면 빠르게 반영하여 수정해보도록 하겠습니다

closed #12

2024-10-29 02:52 UTC, hanbirang requested changes

2024-10-29 02:52 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/config/SecurityConfig.java
> +		//csrf disable
주석 다 지워주세용!

2024-10-29 02:52 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/dto/KakaoResponse.java
> +		return null;
email 받을 수 있을 겁니당 수정해주세요

2024-10-29 02:52 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/dto/OAuth2Response.java
> +	//서비스 제공자
주석 다 제거해주세용

2024-10-29 02:52 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/dto/UserDto.java
> +@Setter
Setter 지양해주세용

2024-10-29 02:52 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/dto/UserDto.java
> +@Setter
그리고 dto는 record 타입으로 해주세용

2024-10-29 02:52 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/jwt/JwtFilter.java
> +			System.out.println("token null");
sout 지양해주세요! Slf4J 어노테이션 선언 후 로그찍을 수 있습니다

2024-10-29 02:52 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/jwt/JwtFilter.java
> +		userDto.setRole(role);
setter 금물!

2024-10-29 02:52 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/jwt/JwtUtil.java
> +		return Jwts.builder()
userId도 jwt에 넣어주세요

2024-10-29 02:52 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/oauth2/CustomSuccessHandler.java
> +	@Override // onAuthenticationSuccess 메소드를 오버라이드해서 사용
주석삭제해주세용

2024-10-29 02:52 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/oauth2/CustomSuccessHandler.java
> +	}
이거대신 `@RequiredArgsContructor`사용해주세요

2024-10-29 02:52 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/oauth2/CustomSuccessHandler.java
> +		response.sendRedirect("<http://localhost:3000/>");
왜 http://localhost:3000로 redirect되나요?

2024-10-29 02:52 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/oauth2/CustomSuccessHandler.java
> +	}
Cookie말고 ResponseCookie로 하셔야 나중에 domain설정가능할겁니당

2024-10-30 05:50 UTC, LEE-GYU-BIN commented on src/main/java/site/sonisori/sonisori/dto/UserDto.java
> +@Setter
아 맞네요 Setter 넵 수정하겠습니다

2024-10-30 05:51 UTC, LEE-GYU-BIN commented on src/main/java/site/sonisori/sonisori/jwt/JwtFilter.java
> +			System.out.println("token null");
넵 알겠습니다!

2024-10-30 05:51 UTC, LEE-GYU-BIN commented on src/main/java/site/sonisori/sonisori/jwt/JwtFilter.java
> +		userDto.setRole(role);
넵!

2024-10-30 05:52 UTC, LEE-GYU-BIN commented on src/main/java/site/sonisori/sonisori/oauth2/CustomSuccessHandler.java
> +		response.sendRedirect("<http://localhost:3000/>");
이건 제가 영상 보면서 공부하다가 작성한건데 여쭤보려고 했습니다 리다이렉트 url을 그냥 localhost:8080으로 잡아두면 될까요?

2024-10-31 02:02 UTC, closed without merging