feat: OAuth2를 이용한 kakao, naver 소셜로그인 구현
sonisori/Server pull request #23
Opened 2024-11-05 01:08 UTC by LEE-GYU-BIN

# Pull requests
### 작업한 내용
```java
#Naver registration
spring.security.oauth2.client.registration.naver.client-name=naver
spring.security.oauth2.client.registration.naver.client-id=
spring.security.oauth2.client.registration.naver.client-secret=
spring.security.oauth2.client.registration.naver.redirect-uri=http://localhost:8080/login/oauth2/code/naver
spring.security.oauth2.client.registration.naver.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.naver.scope=name,email
#provider
spring.security.oauth2.client.provider.naver.authorization-uri=https://nid.naver.com/oauth2.0/authorize
spring.security.oauth2.client.provider.naver.token-uri=https://nid.naver.com/oauth2.0/token
spring.security.oauth2.client.provider.naver.user-info-uri=https://openapi.naver.com/v1/nid/me
spring.security.oauth2.client.provider.naver.user-name-attribute=response
#Kakao registration
spring.security.oauth2.client.registration.kakao.client-name=kakao
spring.security.oauth2.client.registration.kakao.client-id=
spring.security.oauth2.client.registration.kakao.client-secret=
spring.security.oauth2.client.registration.kakao.redirect-uri=http://localhost:8080/login/oauth2/code/kakao
spring.security.oauth2.client.registration.kakao.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.kakao.scope=profile_nickname
#provider
spring.security.oauth2.client.provider.kakao.authorization-uri=https://kauth.kakao.com/oauth/authorize
spring.security.oauth2.client.provider.kakao.token-uri=https://kauth.kakao.com/oauth/token
spring.security.oauth2.client.provider.kakao.user-info-uri=https://kapi.kakao.com/v2/user/me
spring.security.oauth2.client.provider.kakao.user-name-attribute=id

google -> naver로 변경함에 따라 application.properties 부분이 수정되었습니다.

* JwtUtil에 getAuthentication 메서드를 추가했습니다.

* CustomOAuth2Service를 구현했습니다.
   * loadByUserName 메서드를 CustomOAuth2Service 에 구현해놓았습니다.

* TokenFilter를 구현했습니다. 
   * CookieUtil을 가져오는 과정에서 CookieUtil이 Bean으로 등록되어 있지 않아 @Component 어노테이션을 추가했고
이 과정에 따라 생성자로 Value를 주입하는 과정에 문제가 생겨 코드를 수정했습니다.

### PR Point
- 위에 구현 및 수정한 부분이 잘 되었는지 확인해주세요
- CustomOAuth2Service의 loadUser메서드에서 oAuth2UserDto 의 파라미터가 잘 입력됐는지 확인해주세요!

### 📸 스크린샷
- 스크린 샷 혹은 동영상을 첨부해주세요.

| 사진 | 설명 |
| --- | --- |
| | |

### 논의 사항 (선택)
- SuccessHandler 는 구현은 대강 다 해놓았는데 아직 추가는 안했습니다! 위 구현사항이 잘 되면 추가하려고 합니다!

- CustomOAuth2Service의 loadUserByUserame 메서드에서 userDto 객체를 만들때 파라미터를 보시면,
user 엔티티에서 role은 Role 타입인데 userDto에서는 String타입이어서 toString 했습니다 그대로 둘까요?

closed #22

2024-11-05 01:55 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/auth/jwt/JwtFilter.java
> +package site.sonisori.sonisori.auth.jwt;
auth 폴더 하위 jwt 폴더 하위 exception 폴더를 보면 거기에 다른 filter도 있습니다! 그곳에 함께 두는 게 어떨까요??

2024-11-05 01:55 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/auth/jwt/repository/UserRepository.java
> +package site.sonisori.sonisori.auth.jwt.repository;
전체 repository 아래 UserRepository가 있는데 이것을 따로 만든 이유가 있을까요...?

2024-11-05 01:55 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/auth/oauth2/CustomOAuth2Service.java
> +import site.sonisori.sonisori.repository.UserRepository;
이 userRepository를 import해서 오류가 생기고 있는 것 같은데... userRepository 먼저 해결해야 될 것 같네요!

2024-11-05 01:57 UTC, LEE-GYU-BIN commented on src/main/java/site/sonisori/sonisori/auth/oauth2/CustomOAuth2Service.java
> +import site.sonisori.sonisori.repository.UserRepository;
와 그런거였네요 기존 Repository아래 UserRepository를 못보고 따로 만들어서 왜 오류가 나지 하고 있었습니다.. 해결하겠습니다!

2024-11-05 01:57 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/auth/oauth2/CustomOAuth2Service.java
> +package site.sonisori.sonisori.auth.oauth2;
메서드를 분리하여 의미를 나타내는것부터 해보면 어떨까요?
각 라인이 어떤 일을 하는지를 말이죠.
그러면 그때부터 리팩토링과 확장할수 있는 영역들이 보이기 시작합니당

2024-11-05 02:00 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/auth/oauth2/CustomOAuth2Service.java
> +		if (user != null) {
이건 항상 true아닌가요..? 이 조건문이 존재하는 이유를 모르겠습니다!!

2024-11-05 02:08 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/auth/oauth2/dto/NaverResponse.java
> +		this.attribute = attribute;
naver는 response라는 attribute라는 이름에서 가져오는 걸로 알고 있는데 그냥 가져와도 되나요??

2024-11-05 02:14 UTC, LEE-GYU-BIN commented on src/main/java/site/sonisori/sonisori/auth/oauth2/CustomOAuth2Service.java
> +		if (user != null) {
지정한 username이 DB에 없으면 findByUsername 메서드가 null을 반환해서 그렇게 설정했습니다! 
그래서 원래는 loadUserByUsername이 default return 으로 null을 반환하는게 아니라 
throw new UsernameNotFoundException(); 로 하려고 했는데 그럴 필요가 없을까요?

2024-11-05 02:15 UTC, hanbirang requested changes
일단 1차적으로 코드 확인했습니다!! SuccessHandler 추가하시면 다시 또 확인하겠습니다!
또, dto에서 String이 아닌  이미 만들어놓은 Enum으로 추가하는게 좋을 것 같네요
저희 데이터베이스 구조를 보시면 social type도 넣게되어있습니다
따라서 이것도 추가해주시면 좋을 것 같아용 
또 `common` 폴더를 보니까 enum들이 너무 정리가 안되어있는것같아서 `common` 폴더 하위 `enums` 폴더를 만들어서 `Difficulty`, `Role`, `SocialType` 을 정리하는 것도 좋을 것 같은데 어떻게 생각하시나요?

2024-11-05 02:21 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/auth/oauth2/CustomOAuth2Service.java
> +		if (user != null) {
`findByUsername` 메서드를 `Optional`로 받으면 가져옴과 동시에 에러 처리를 할 수 있습니다! 또한 이미 throws로 에러 처리를 하고 있으므로 없으면 바로 에러처리가 될 겁니다 그럼 저 조건문은 무조건 true가 되어서 필요없는 코드로 보여요! 그리고 그냥 가져오는 것데 userDto가 필요할까요??? 그냥 바로 user로 가져오면 되는데 dto를 생성한 이유가 있을까요??

2024-11-05 02:40 UTC, LEE-GYU-BIN commented on src/main/java/site/sonisori/sonisori/auth/oauth2/CustomOAuth2Service.java
> +		if (user != null) {
CustomOAuth2User에 userDto와 User를 담아서 return 하기 때문에 userDto를 생성해서 값들을 담아줬습니다. 그렇지 않으면 null값을 넣어줘야 할 것 같은데 상관 없을까요 ? 

그러면 findByUsername을 Optional로 받아서 처리하는 걸로 수정하면 될까요? 조건문은 없애구요!

2024-11-05 02:45 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/auth/oauth2/CustomOAuth2Service.java
> +		if (user != null) {
네 optional로 받고 null 이면 바로 에러처리가 뜨게 하면 될 것 같아용
어차피 에러처리가 먼저 되기 때문에 null이 들어갈 일이 일어나지 않을 것 같습니당

2024-11-06 00:20 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/auth/oauth2/CustomOAuth2Service.java
> +			oAuth2Response.getEmail(), SocialType.valueOf(oAuth2Response.getProvider()));
Role이랑 SocialType에서 오류가 나는 것 같은데 해결먼저 해야되지 않을까요??

2024-11-06 00:36 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/auth/oauth2/CustomOAuth2SuccessHandler.java
> +		response.sendRedirect("http://localhost:8080/login/oauth2/code/");
redirect url은 클라이언트 url로 설정하는 것이 일반적입니다 또한 만약 redirect url을 이렇게 하드코딩 할 경우 url이 변경될때마다 코드를 수정해야되지 않을까요? 따라서 설정 변수로 설정하는 것이 일반적입니다 application.properties에서 가져오는 것이 어떨까요?

2024-11-06 07:28 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/auth/oauth2/CustomOAuth2Service.java
> +public class CustomOAuth2Service extends DefaultOAuth2UserService implements UserDetailsService {
한 메서드가 하는 일이 너무 많은 것 같습니다... 물론 로직상 문제는 없지만 백엔드에서 할 일이 많지 않은 만큼 클린코드를 지향하면 어떨까요?

2024-11-06 07:42 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/auth/oauth2/CustomOAuth2Service.java
> +			.orElseThrow(() -> new UsernameNotFoundException(username));
근데 여기서 오류를 발생시키는 게 맞을까요? 만약 존재하지 않으면 회원가입을 하고, 존재하면 로그인을 시키는 게 oauth2 로직아닌가요? 어떤 로직으로 작성하신 건지 궁금합니당 현재 로직은 어떻게 되고 있나요?

2024-11-06 07:44 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/auth/oauth2/CustomOAuth2Service.java
> +		}
if보단 switch가 더 성능상 좋을지도..~

2024-11-06 13:42 UTC, LEE-GYU-BIN commented on src/main/java/site/sonisori/sonisori/auth/oauth2/CustomOAuth2Service.java
> +			.orElseThrow(() -> new UsernameNotFoundException(username));
말씀하신대로 존재하지 않으면 어차피 DB를 탐색할 일이 없기 때문에 오류가 발생할 일이 없을 것 같습니다.. 
제가 저렇게 작성한 이유는 위에서 findByUsername을 Optional로 받고 null이면 바로 에러처리가 뜨면 좋을 것 같다고 하셔서 바로 null일때 에러 처리를 하게 만든건데 그냥 그렇게 할 필요가 없을까요?

2024-11-06 13:44 UTC, LEE-GYU-BIN commented on src/main/java/site/sonisori/sonisori/auth/oauth2/CustomOAuth2Service.java
> +			.orElseThrow(() -> new UsernameNotFoundException(username));
우선 해당사항은 더 여쭤봐야될 것 같아서 나머지만 먼저 업데이트하겠습니다!

2024-11-06 13:52 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/auth/oauth2/CustomOAuth2Service.java
> +			.orElseThrow(() -> new UsernameNotFoundException(username));
오류가 발생해야 하나요?

2024-11-06 13:54 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/auth/oauth2/CustomOAuth2Service.java
> +			.orElseThrow(() -> new UsernameNotFoundException(username));
아래의 loadUserByUsername은 기존의 user를 가져와서 정보를 가져오는 것이므로 오류가 발생해야 합니다 하지만 `loadUser`의 경우 오류가 발생하면 안 되지 않나요??

2024-11-06 14:00 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/auth/oauth2/CustomOAuth2Service.java
> +			.orElseThrow(() -> new UsernameNotFoundException(username));
아래의 `loadUserByUsername`의 경우 username으로 사용자 정보를 찾아오는 메서드 입니다. 따라서 만약 저희 회원이 아니라면 사용자 정보가 없으니 에러 처리를 하는게 맞습니다 음.. 아무래도 이 부분이 복잡하고 메서드 명이 비슷하다보니 헷갈리신 것 같네욤 ㅠ 혹시 제가 회원가입 로직을 발견하지 못한 거라면 말씀해주세요!

2024-11-06 14:17 UTC, hanbirang reviewed
oauth2Handler와 service가 생성되었으니 security config에 추가해주셔야 됩니다! 
아래는 예시입니다!! 따라서 저희랑 메서드 명이나 파일명이 달라요 이런 식으로 추가해주세요! 
또한 url도 수정이 되어야 합니다. 
```java
http
			.csrf(AbstractHttpConfigurer::disable)
			.formLogin(AbstractHttpConfigurer::disable)
			.httpBasic(AbstractHttpConfigurer::disable)
			.addFilterBefore(new JwtFilter(cookieUtil, jwtUtil),
				UsernamePasswordAuthenticationFilter.class)
			.addFilterBefore(jwtExceptionFilter, JwtFilter.class)
			.oauth2Login((oauth2) ->
				oauth2.userInfoEndpoint(
						userInfoEndpointConfig ->
							userInfoEndpointConfig.userService(customOAuth2UserService))
					.successHandler(customOAuth2Handler)
			)
```
또한 현재
```java
.authorizeHttpRequests((auth) -> auth
				.requestMatchers("/").permitAll()
				.anyRequest().authenticated())
```
이런 식으로 되어있는데요 여기서 requestMatcher안의 내용을 `"/login/oauth2/code/*"`이런 식으로 변경해줘야 좋을 것 같습니당 해당 url만 인증안해도 사용가능하고 나머지는 로그인을 해야하게끔요

2024-11-09 11:16 UTC, hanbirang reviewed
코드 확인했습니다!
개행 부분들은 코드 스타일에 관한 부분이라 참고만 해주시면 좋을 것 같아용
또, redirect url 어떻게 설정하셨는지 알려주세요!
이 코드 마무리 되면 프론트 코드 짜고 테스트 이후에 approve 하도록 하겠습니다! 그때 merge해주시면 좋을 것 같습니다

추가로.. 한 가지만 이야기하자면 현재 브랜치 명이 저희 컨벤션과 맞지 않습니당 
다음 작업하실 때는 컨벤션에 맞게 작성해주시면 좋을 것 같아요! 일단 어차피 이 브랜치의 작업이 머지되면 브랜치는 삭제할 것이기 때문에 수정할 필요는 없을 것 같습니다!
그리고 이슈의 경우 어떤 작업을 하는지 알 수 있는 역할을 합니다. 하지만 현재 해당 이슈의 제목이 너무 긴것같아요 그래서 가독성이 떨어집니다 다음 작업을 진행하실 때에는 조금 더 간단하게 써주시면 좋을 것 같아요!

2024-11-09 11:16 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/auth/oauth2/CustomOAuth2Service.java
> +		user.signUp(username, oAuth2Response.getName(), oAuth2Response.getEmail());
이거도 개행이 있으면 좋을 것 같네요!

2024-11-09 11:16 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/entity/User.java
> +	}
다른 부분들의 기본값을 넣어주어야 할 것 같네요
notnull인 값들이요 
회원가입해서 db에 user의 정보가 들어갈 때 어느 정보들이 있어야되는지를 생각해보시면 될 것 같습니다!

2024-11-10 18:20 UTC, LEE-GYU-BIN commented on src/main/java/site/sonisori/sonisori/entity/User.java
> +	}
넵 시간이 늦어서 redirect url은 내일 카톡으로 발송하겠습니다!!

2024-11-11 00:13 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/entity/User.java
> +	}
넵! redirect url은 사실 기밀사항은 아니라서 그냥 여기에 적어주셔도 되긴합니당

2024-11-11 10:55 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/auth/jwt/JwtUtil.java
> +		UserDetails userDetails = customOAuth2Service.loadUserByUsername(getUserId(token).toString());
`loadUserByUsername`에서는 username으로 찾고있는데 userId로 가져오니까 계속 오류가 발생하네요! 이부분 수정해주셔야될것같습니당

2024-11-11 11:01 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/common/enums/SocialType.java
> +	naver, kakao
그리고 여기다 `none`도 추가해주세요

2024-11-11 11:33 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/auth/jwt/JwtUtil.java
>  	public String createAccessToken(User user) {
여기서 claim에 username을 추가해줘야겠네용

2024-11-11 11:34 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/auth/jwt/JwtUtil.java
> +
이 부분을 getUsername함수로 바꾸면 될 것 같네요!
```suggestion
	public Long getUsername(String token) {
		Claims claims = extractClaims(token);
		return claims.get("username", String.class);
	}

```

2024-11-11 12:12 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/common/SocialType.java
> +package site.sonisori.sonisori.common;
enums폴더에 있어야되지않나용?

2024-11-11 13:16 UTC, merged