feat: 마이페이지 조회, 수정 api 구현
sonisori/Server pull request #40
Opened 2024-11-16 15:19 UTC by LEE-GYU-BIN

# Pull requests
### 작업한 내용
- 마이페이지 조회, 수정 api를 구현했습니다.

### PR Point
-  마이페이지 수정할때 이름을 입력받은 부분에서 에러처리를 제 나름대로 했는데 완벽하지 않은 것 같습니다.
UserService에 추가한 updateUserName 메서드의 에러처리 부분을 확인해주시면 감사하겠습니다!

### 📸 스크린샷
- 스크린 샷 혹은 동영상을 첨부해주세요.

| 사진 | 설명 |
| --- | --- |
|![image](https://github.com/user-attachments/assets/c465f218-acd0-4110-904a-c4fc852906c8) | 조회 성공 |
|![image](https://github.com/user-attachments/assets/997b686e-d1a0-4b50-9a02-12f70dee4d8e) | 수정 성공 |
| ![image](https://github.com/user-attachments/assets/e26bd6bd-7295-4363-924c-ca955d3c0eb9) | DB에서 이름 수정된 모습 |

### 논의 사항 (선택)
- 처음에 Object mapper의 존재를 몰랐다가 오류 수정을 하다가 존재를 알게되어서 추가해서 구현했습니다.
- 제가 에러처리한 부분으로 닉네임이 중복되거나 길이를 초과하거나 공백이 입력되면 500 에러가 발생합니다.

closed #35

2024-11-17 00:35 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/controller/UserController.java
> +		ObjectMapper objectMapper = new ObjectMapper();
이게 왜 필요하나요..??? dto 생성해서 사용하시면 되지 않나요? 그럼 에러처리 문제도 해결될 것 같네요

2024-11-17 00:47 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/service/UserService.java
> +			.orElseThrow(() -> new IllegalArgumentException("User not found with id: " + userId));
이런 에러 문구들이.. 사용자 친화적이지는 않은 것 같다는 생각이 드네요! 또한 이런 문구들은 상수들로 처리를 하는 경우가 많습니다. `ErrorMessage` 파일 참고해주세요

2024-11-17 00:47 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/service/UserService.java
> +		}
이 예외로 지정하신 이유가 있을까요?

2024-11-17 00:48 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/service/UserService.java
> +			.orElseThrow(() -> new IllegalArgumentException("User not found with id: " + userId));
또한 새로운 이름에 대한 ... 예외처리를 하기전에 user에 대한 검증을 하는 게 우선이 아닐까요?

2024-11-17 00:49 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/dto/user/UpdateUserNameRequest.java
> +}
notion에 적어둔 규칙 확인해주세요! 입력값에 대한 검증은 request일 경우에 dto에 하는 것으로 적어두었습니당

2024-11-17 00:50 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/controller/UserController.java
> +		userService.updateUserName(userDetails.getUserId(), updateUserNameRequest.name());
이름을 controller에서 직접 꺼내기보단.. service로 dto 자체를 넘겨주기!

2024-11-17 00:58 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/controller/UserController.java
> +			userDetails.getSocialType().toString());
controller에서 이 로직을 담당하는 게 맞을까요? controller에서는 데이터를 가공하는 로직이 있으면 안됩니다 service 계층에서 작업해야되는게 아닐까하는 생각이 드네요

2024-11-17 00:59 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/auth/CustomUserDetails.java
> +	}
mypage에서 조회하기 위해 이 메서드를 추가하는 것은.. 불필요하지 않을까요? 어차피 userId를 통해 user를 꺼내올 수 있고 user에서 getSocialType을 하면 되는데 이걸 추가하신 이유가 있나요???

2024-11-17 01:12 UTC, hanbirang requested changes
예상치못한 에러나 지정한 에러가 아닌 이상 500 에러가 뜨면 절대!! 안 됩니당 필요한 에러의 경우 직접 에러를 생성해서라도 커스텀 예외처리가 되도록 해야돼요!! 일단 1차적으로 수정해주셨으면 하는 부분들 남겨놨습니당 

또한 이 아래에 적는 내용들은 그저... 클린 코드를 위한 리뷰입니다 읽어보시고, 규빈님 생각에 맞게 반영해주시면 좋을 것 같아요! 

마이페이지 조회나 수정의 경우 대체로 많이 사용하는 변수명이나 메서드 명은 
`UserProfile`, `MyPage`, `UserInfo` 인 것 같아요
UI와 사용자 경험 중심 프로젝트, 또 국내의 경우 `MyPage`를 쓰는 것 같습니다 다만 데이터의 성격보다는 화면과 페이지 중심이죠. `UserInfo`와 `UserProfile`의 경우 데이터 중심이지만 userInfo가 조금 더 구체성이 떨어집니다 사용자에 대한 정보의 범위는 넓으니까요 
글로벌 프로젝트나 프레임워크에서는 `profile`이라는 용어를 많이 사용합니다 oauth2 스펙에서도 profile이라는 스코프를 사용해 사용자 정보를 요청하는 것처럼요 

하지만 저희가 글로벌 프로젝트는 아니니... 그냥 정보 제공차 리뷰남겼습니다!

2024-11-17 08:45 UTC, LEE-GYU-BIN commented on src/main/java/site/sonisori/sonisori/controller/UserController.java
> +		ObjectMapper objectMapper = new ObjectMapper();
@RequestBody를 이용해서 그냥 String newName 으로 받아서 바로 넘기니까 JSON으로 날라온 내용을 그 안에서 추출하지 못하고 전체 다 길이로 인식을 해버려서 계속 오류가 발생하더라구요. 그래서 ObjectMapper를 추가하고 Spring이 JSon내용을 정확하게 String만 추출하도록 수정했습니다. 이렇게 하면 안되는건가요 ?

2024-11-17 08:46 UTC, LEE-GYU-BIN commented on src/main/java/site/sonisori/sonisori/service/UserService.java
> +			.orElseThrow(() -> new IllegalArgumentException("User not found with id: " + userId));
user에 대해서 검증하기 이전에 새로운 이름이 애초에 잘못 입력되면 저 로직자체를 수행하지 않게 했는데 그것보다 user 검증을 먼저하는게 낫나요?

2024-11-17 08:50 UTC, LEE-GYU-BIN commented on src/main/java/site/sonisori/sonisori/controller/UserController.java
> +			userDetails.getSocialType().toString());
이게 위에 말씀하신 부분이랑 연계되는 건가요? Service단에서 작업을 수행하도록 하겠습니다

2024-11-17 08:53 UTC, LEE-GYU-BIN commented on src/main/java/site/sonisori/sonisori/auth/CustomUserDetails.java
> +	}
제가 이 부분을 찾아보면서 좀 고민했는데요 . User 엔티티에서 조회하는게 데이터베이스에 부담을 줄 수 있으므로 (물론 이 경우 아닐 수 있지만) 간단하게 소셜타입만 반환하는게 목적이라면  Dto에서 꺼내오는게 더 효율적일 수 있다고 해서 이렇게 작성해봤는데 추가할 필요가 없을까요?

2024-11-17 09:19 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/controller/UserController.java
> +		ObjectMapper objectMapper = new ObjectMapper();
dto를 생성한 이유가 이럴 때 사용하라고 있는 것입니당

2024-11-17 09:21 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/service/UserService.java
> +			.orElseThrow(() -> new IllegalArgumentException("User not found with id: " + userId));
user자체가 잘못되면 새로운 이름을 입력조차 못하지 않을까요?

2024-11-17 09:21 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/service/UserService.java
> +		}
동일한 이름이 입력되면 무시하면 되지않을까요? 굳이 에러를 발생시킬 필요를 모르겠습니다!

2024-11-17 09:37 UTC, LEE-GYU-BIN commented on src/main/java/site/sonisori/sonisori/service/UserService.java
> +			.orElseThrow(() -> new IllegalArgumentException("User not found with id: " + userId));
아 애초에 입력전에 정보를 가져와야해서 그런거군요 이해했습니다! 감사합니다

2024-11-17 09:38 UTC, LEE-GYU-BIN commented on src/main/java/site/sonisori/sonisori/controller/UserController.java
> +		ObjectMapper objectMapper = new ObjectMapper();
아 그럼 dto를 사용하면 알아서 json형식대로 추출되는건가보네요 감사합니다

2024-11-17 09:51 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/auth/CustomUserDetails.java
> +	}
`getSocialType()`을 User 엔티티에서 호출하는 것은 사실 엔티티에 이미 포함된 값이고, DB에서 이미 로드된 정보이므로 추가적인 조회 비용이 발생하지 않을 것 같네요!

2024-11-18 02:39 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/controller/UserController.java
> +		UserProfileResponse userProfileResponse = userService.setUserProfileResponse(userDetails);
CustomUserDetails 객체를 보내서, 서비스 계층에서 이 객체를 사용하는 대신 필요한 정보만 전달하는 게 좋습니다 서비스 계층이 특정 구현체에 의존하지 않도록요

2024-11-18 02:40 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/controller/UserController.java
> +		userService.updateUserName(userDetails, updateUserNameRequest);
여기도 마찬가지용

2024-11-18 02:42 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/service/UserService.java
> +		User user = userRepository.findById(customUserDetails.getUserId()).orElseThrow(InvalidUserException::new);
InvalidUserException의 오류 메시지는 `회원 정보가 잘못되었습니다.`일 텐데... 그리고 혹시 user 객체가 없으면 401에러가 뜨는 게 맞을까요?

2024-11-18 02:43 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/service/UserService.java
> +	public UserProfileResponse setUserProfileResponse(CustomUserDetails userDetails) {
`set`은 값을 변경하거나 설정하는 작업을 연상시킵니다 하지만 이 메서드는 단순히 데이터를 가공하여 반환하므로 create같은 명칭으로 변경하는게 더 적합하다고 생각하는데, 어떻게 생각하시나요?

2024-11-18 06:58 UTC, LEE-GYU-BIN commented on src/main/java/site/sonisori/sonisori/service/UserService.java
> +		User user = userRepository.findById(customUserDetails.getUserId()).orElseThrow(InvalidUserException::new);
제가 에러처리를 좀 헷갈려서 제대로 구현을 못한것같습니다 해당사항에 맞춰 수정하겠습니다!

2024-11-18 07:27 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/controller/UserController.java
> +		userService.updateUserName(userId, name);
updateUserName으로 dto자체를 보내면되지않을까요?? userId랑요

2024-11-18 07:28 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/exception/UserNotFoundException.java
> +}
NotFoundException이라는 에러가 있습니다 기존의 에러를 사용하면 어떨까요?

2024-11-18 07:29 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/controller/UserController.java
> +		UserProfileResponse userProfileResponse = userService.createUserProfileResponse(name, socialType);
여기서도 그냥 UserDetails에서 userId를 꺼내서 넘겨주고 service에서 꺼내면될것같습니다

2024-11-19 02:32 UTC, hanbirang approved these changes
코드확인했습니다! 고생하셨습니다

2024-11-19 02:37 UTC, merged