feat: 관리자 토픽 추가 api구현
sonisori/Server pull request #46
Opened 2024-11-21 03:26 UTC by LEE-GYU-BIN

# Pull requests
### 작업한 내용
- 관리자 토픽 추가 api를 구현하였습니다.
- 본래 Request Body에 토픽 title과 토픽 contents 만 넘어오는 것으로 되어있었으나 difficulty도 함께 설정하는게 맞는 것 같아 difficulty도 Dto에 추가해서 구현하였습니다. (함께 설정하는게 아니라면 수정하겠습니다)

### PR Point
- 예외처리부분에서 놓친게 없나 확인해주세요

### 📸 스크린샷
- 스크린 샷 혹은 동영상을 첨부해주세요.

| 사진 | 설명 |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/e5b22f68-d37d-4ace-911e-98f6a6700886) | api호출시 topicId 반환 |
| ![image](https://github.com/user-attachments/assets/f75b4056-98a9-4c1e-b008-e44676b91bdb) | db에도 저장된 모습 |

### 논의 사항 (선택)
- topicId가 3인 이유는 제가 앞서 테스트하느라 2개를 확인하고 나서 DELETE로 비우고 다시 저장해서 그렇습니다..

closed #45

2024-11-21 11:35 UTC, hanbirang requested changes

2024-11-21 11:35 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/controller/SignTopicController.java
> +	@PostMapping("/admin/topics")
지금 현재 user의 role이 admin인 user만 사용할 수 있게 되어있나요? 아닌 것 같아서요 이렇게되면 일단 user도 해당 api를 호출하여 토픽을 추가할 수 있지 않을까요?

2024-11-21 11:35 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/controller/SignTopicController.java
> +	public ResponseEntity<Map<String, Long>> addSignTopic(@Valid @RequestBody AddSignTopicRequest signTopicRequest) {
Map이 아니라 dto 사용하세요

2024-11-21 11:35 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/dto/signtopic/AddSignTopicRequest.java
> +	String topicName,
api 명세서 수정을 안했는데 domain의 필드 명과 맞추는 것이 좋을 것 같습니다

2024-11-24 07:54 UTC, hanbirang commented
테스트해봤을 때 지금 잘 되고 있나요?

2024-11-24 15:46 UTC, LEE-GYU-BIN commented
넵 테스트 결과 잘 되고 있습니다. security config 상에 admin 권한을 해제하고 입력하면 db에 잘 저장되다가 권한 설정 후 실행하면 오류가 401 Unauthorized 로 발생하면서 입력이 안되는데 이 때 메세지가 "토큰이 존재하지 않습니다" 여서 이대로 냅둬도 되는지 이게 궁금합니다!

2024-11-25 00:19 UTC, hanbirang commented
admin 권한을 해제하고 입력하면 잘 된다는 게 무슨 뜻인지 모르겠어요...
이건 admin 역할만 되는 거니까 권한을 해제하고 입력하면 안 되지 않을까요?

2024-11-25 02:30 UTC, LEE-GYU-BIN commented
아 그러니까 제 코드가 잘 되는지 테스트 해보려고 security config에 hasRole 부분을 없애고 해보고, 다시 넣고 해보고 비교해봤다는 말이었습니다. Admin역할만 되게 설정하고 하면 일반 USER는 안되는걸 잘 확인했다는 뜻이었습니다!

2024-11-25 06:28 UTC, LEE-GYU-BIN commented
안되네요... 해결하겠습니다..

2024-11-26 14:50 UTC, LEE-GYU-BIN commented
며칠동안 계속 찾은 끝에 성공했습니다..! 테스트도 다 성공적으로 되는 것 확인했습니다!

2024-11-27 00:17 UTC, hanbirang commented
넵 수고하셨습니다! 근데 과연 토큰이 존재하지 않는다는 에러가 맞을까요?? 403 에러가 떠야할 것 같은데요 user의 경우 접근 권한이 없으니까요

2024-11-27 12:03 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/service/SignTopicService.java
> +
데이터 무결성과 안정성 보장을 위해 `@Transactional` 어노테이션을 추가하는 것은 어떨까요?

2024-11-27 13:00 UTC, merged