Feature/2 create entity
sonisori/Server pull request #7
Opened 2024-10-19 12:40 UTC by LEE-GYU-BIN

# Pull requests
### 작업한 내용
- 프로젝트에서 사용할 모든 데이터베이스 테이블과 매핑되는 엔티티 클래스구현을 완료했습니다.

### PR Point
- 어노테이션 잘못 활용했거나 빠진게 없는지 중점적으로 확인해주세요.
- Data Entity의 STAMP 부분은 문제가 없는지 확인해주세요
- 매핑 관계를 잘 작성했는지 확인해주세요.

### 📸 스크린샷
- 스크린 샷 혹은 동영상을 첨부해주세요.

| 사진 | 설명 |
| --- | --- |
| | |

### 논의 사항 (선택)
- 

closed #2

2024-10-19 13:48 UTC, hanbirang requested changes
시험 공부하시느라 바쁘실 텐데 정말 수고하셨습니다!
다만, 몇 가지 제안 사항과 수정 사항이 있는 것 같아 Request를 요청하였습니다.
공통된 사항은 한 번만 리뷰를 남겼습니다.

또한, main이 머지되지 않은 것 같습니다. build.gradle에도 수정해야 할 사항이 있는 것 같은데, 그 점이 반영되지 않은 것 같습니다. 따라서 먼저 git merge main으로 머지한 후, build.gradle 수정 사항이 있으면 추가하여 push해 주시면 좋겠습니다.

마지막으로, PR 제목이 저희 PR 컨벤션과 맞지 않아 수정해 주시면 감사하겠습니다!

2024-10-19 13:48 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/entity/Data.java
> +	private Timestamp updateAt;
`updateAt` 오타 확인했습니다! `updatedAt`으로 수정부탁드려요!

2024-10-19 13:48 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/entity/Data.java
> +public abstract class Data {
`Data` 라는 클래스 명이 모호한 것 같아요! `BaseEntity` 혹은 `DateEntity` 등 클래스 명을 수정하는 것은 어떨까요??

2024-10-19 13:48 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/entity/Data.java
> +	private Timestamp createdAt;
`Timestamp` 대신 `LocalDateTime`을 사용하는 것은 어떨까요?? Java 8 이후로는 `java.time` 패키지를 많이 사용한다고 합니다! 
https://doingsomething.tistory.com/m/108

2024-10-19 13:48 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/entity/History.java
> +public class History extends Data {
클래스 이름도 테이블 명을 그대로 따라가는 것은 어떨까요? 대신 단수로요!
`QuizHistory` 이런 식으로요!
혹시 나중에 학습 기록같은 것을 저장할 때를 대비하여 명확히 명시하는 것이 좋을 것 같습니다! 규빈님 의견은 어떠신가용?

2024-10-19 13:48 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/entity/History.java
> +	@GeneratedValue(strategy = GenerationType.IDENTITY)
`@GeneratedValue(strategy = GenerationType.IDENTITY)`일 경우 ID가 자동 생성되므로 id에서는 `@NotNull`이 불필요하긴 합니당 클린 코드를 위해서 제거하는 것은 어떨까용??

2024-10-19 13:48 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/entity/History.java
> +	private Topic topic;
이 변수명도 명시성을 위해서 테이블과 맞추는 것이 좋다고 생각합니다!
`SignTopic` 이런 식으로요!! 어떻게 생각하시나욤?

2024-10-19 13:48 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/entity/History.java
> +	@ManyToOne
`@ManyToOne`의 경우 기본값이 `EAGER`인데요 이 경우 성능 이슈를 유발할 수가 있어요!
따라서 `fetch=FetchType.LAZY`를 명시적으로 설정해주는 것이 좋을 것 같아요!
`@ManyToOne(fetch = FetchType.LAZY` 이런 식으로요

2024-10-19 13:48 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/entity/Quiz.java
> +public class Quiz extends Data {
이 클래스명도 테이블과 맞추는 것이 좋다고 생각하는데 어떻게 생각하시나욤?
`SignQuiz` 처럼요!

2024-10-19 13:48 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/entity/Quiz.java
> +	private String sentece;
`sentece` 오타 확인했습니다!
그리고 `@Column`에서 사용하는 `length`의 경우 컬럼정의에만 영향을 미치고 유효성 검사는 수행하지 않습니다
따라서 유효성 검사를 위해서는 `@Size` 어노테이션을 별도로 사용하는 것이 좋을 것 같은데 어떻게 생각하시나요?? `@Size(max = 255)` 이런 식으로요!

또 문자열 필드의 경우에는 `@NotNull` 보다 `@NotBlank`를 사용하는 것이 더 적절합니다!
낫널의 경우 값이 null 만 아니라면 통과이지만 낫블랭크의 경우 빈문자열이나 공백일 경우도 유효성 검사를 해주기 때문이에요! 따라서 수정하면 더 좋을 것 같은데 어떻게 생각하시나요?

2024-10-19 13:48 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/entity/Topic.java
> +public class Topic extends Data {
이것도 테이블명의 단수 형태인 `SignTopic`은 어떨까요?

2024-10-19 13:48 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/entity/Topic.java
> +	}
`Difficulty` 같은 enum의 경우 다른 곳에서 사용할 수도 있어서요 차라리 `constants` 폴더 하위에서 따로 관리하는 것은 어떨까요? 파일로 따로 만들어서 별도로 관리하면 좋을 것 같습니당 enum 타입을 별도의 파일로 관리하면 재사용성이나 모듈성, 가독성 측면에서 장점이 있다고 합니다!

2024-10-19 13:48 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/entity/Word.java
> +	private Long Id;
`Id` 오타 확인했습니다! 
또한 `NotNull`은 제거하고 `@GeneratedValue(strategy = GenerationType.IDENTITY)` 를 추가하는 것이 좋을 것 같아요!

2024-10-19 13:48 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/entity/Word.java
> +public class Word {
이것도 `SignWord`로 수정하는 것은 어떨까요?

2024-10-19 13:48 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/entity/Topic.java
> +	private List<History> historyList; // User의 histories와 구분
구분을 위해서 `historyList`로 정했다고 하셨는데 목적을 명확하게 구분하기 위하여 `topicHistories`로 하는 건 어떨까요? 통일성을 위해 `user`에는 `userHistories`로 짓고요 !

2024-10-19 14:18 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/entity/Topic.java
> +	private List<History> historyList; // User의 histories와 구분
아니면 사실 객체가 달라서 그냥 histories로 통일해도 될 것 같긴 합니다..! 흠 조금 더 생각해봐야겠네용

2024-10-21 06:39 UTC, LEE-GYU-BIN commented on src/main/java/site/sonisori/sonisori/entity/Data.java
> +public abstract class Data {
저도 그래서 처음에 DataEntity 로 하려다가 Data로 했는데 클래스명 수정 좋은 것 같습니다! common 폴더라고 하신건 Entity 폴더랑 같은 위치에 두는걸 말씀하시는걸까요? sonisori/entity sonisory/common 이런식일까요?

2024-10-21 06:39 UTC, LEE-GYU-BIN commented on src/main/java/site/sonisori/sonisori/entity/Data.java
> +	private Timestamp createdAt;
참고해서 수정하겠습니다!

2024-10-21 06:40 UTC, LEE-GYU-BIN commented on src/main/java/site/sonisori/sonisori/entity/History.java
> +public class History extends Data {
나름대로 명확히한다고 지은건데 생각해보니 나중에 더 세분화를 고려하면 더 명확히 하는게 맞을 것 같네요 수정하겠습니다!

2024-10-21 06:41 UTC, LEE-GYU-BIN commented on src/main/java/site/sonisori/sonisori/entity/History.java
> +	@GeneratedValue(strategy = GenerationType.IDENTITY)
앗 몰랐습니다 알겠습니다

2024-10-21 06:42 UTC, LEE-GYU-BIN commented on src/main/java/site/sonisori/sonisori/entity/Quiz.java
> +	private String sentece;
어.. 이것도 몰랐습니다 좋은 내용인 것 같아요 수정하겠습니다

2024-10-21 06:43 UTC, LEE-GYU-BIN commented on src/main/java/site/sonisori/sonisori/entity/Topic.java
> +	}
알겠습니다!

2024-10-21 07:39 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/entity/Data.java
> +public abstract class Data {
네 맞습니다!

2024-10-21 07:59 UTC, LEE-GYU-BIN commented on src/main/java/site/sonisori/sonisori/entity/Topic.java
> +	private List<History> historyList; // User의 histories와 구분
객체가 다르긴한데 한비님이 처음에 하신 말처럼 topicHistories, userHistories가 직관적으로 이해하기 좋은 것 같은데 어떠세요 ?

2024-10-21 10:08 UTC, hanbirang reviewed
수고하셨습니다!
다만, 지금 Column 어노테이션에서 length가 있는 것도 있고 없는 것도 있더라고요!
차라리 Size로 길이를 알 수 있으니 length를 전체적으로 지우는 것이 코드 일관성을 유지하는데 도움이 되지 않을까.. 싶습니당!

2024-10-21 10:08 UTC, hanbirang commented on build.gradle
> +    // entity
사소한 사항이지만 여기는 위의 spring boot starter에서 제공하는 것들과 같은 분류이기도 해서 굳이 주석달지 않아도 될 것 같아요! validation이 entity에만 쓰이는 것은 아니라서... 그냥 위랑 같이 붙여서 적으면 좋을 것 같습니다!

2024-10-21 10:08 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/common/DataEntity.java
> +public abstract class DataEntity {
`Data`인 이유가 있나용..? 날짜와 관련된 엔티티라서 `Date`가 맞지 않을까 싶어서요!

2024-10-21 10:08 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/constants/Difficulty.java
> +package site.sonisori.sonisori.constants;
ㅠ 죄송해요 제가 실수했어요 enum들을 constants가 아니라.. common 하위의 폴더에 넣으면 어떨까..를 잘 못 적었습니다...ㅠㅠ

2024-10-21 10:08 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/entity/SignTopic.java
> +	private List<QuizHistory> topicHistories; // User의 histories와 구분
주석 삭제해주세요!

2024-10-21 10:08 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/entity/SignWord.java
> +	@Column(name = "word", length = 50)
NotBlank로 수정하고 Size 추가해주세요!

2024-10-21 11:04 UTC, LEE-GYU-BIN commented on src/main/java/site/sonisori/sonisori/common/DataEntity.java
> +public abstract class DataEntity {
공통으로 사용하는 데이터라고 생각해서 그렇게 했는데 Date가 더 나을까요?

2024-10-21 11:04 UTC, LEE-GYU-BIN commented on src/main/java/site/sonisori/sonisori/constants/Difficulty.java
> +package site.sonisori.sonisori.constants;
괜찮습니다 수정하겠습니다 ㅎ

2024-10-21 11:05 UTC, LEE-GYU-BIN commented on src/main/java/site/sonisori/sonisori/constants/Difficulty.java
> +package site.sonisori.sonisori.constants;
아 혹시 common 폴더 밑에 또 폴더를 만들면 좋겠다는 말씀이신가요? 아니면 common 에 집어넣으면 좋겠다는 말씀이실까요?

2024-10-21 11:05 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/common/DataEntity.java
> +public abstract class DataEntity {
음 저는 그렇게 생각해요! common 디렉토리를 통해 공통으로 사용한다는 것을 알 수 있을 것이고, 공통으로 사용하는 어떤 엔티티인지를 한눈에 알아보기 위해서 Date가 더 좋을 것 같습니다!

2024-10-21 11:07 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/constants/Difficulty.java
> +package site.sonisori.sonisori.constants;
common 폴더에 넣으면 좋을 것 같아요!

2024-10-21 11:09 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/entity/SignQuiz.java
> +	@Column(name = "senetece")
column 이름 오타 확인했습니다!

2024-10-21 11:13 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/entity/User.java
> +	private List<QuizHistory> userHistories;
음.. 그리고 사실 서로 다른 객체가 quizHistories를 갖는 것이므로 변수명을 똑같이 `quizHistories`로 통일해도 괜찮을 것 같아요! 오히려 코드가 통일성있을 것 같습니다! 저희가 모든 entity에서 id라는 동일 변수를 쓰고있잖아요? 그거랑 같은 맥락이라고 보면 될 것 같은데 규빈님 생각은 어떠신가요?

2024-10-21 11:13 UTC, hanbirang commented on src/main/java/site/sonisori/sonisori/entity/QuizHistory.java
> +	private int count;
count의 경우 음수는 될 수 없으므로 `@Min(0)` 같은 제약 조건을 추가하는 것은 어떨까요?

2024-10-21 11:26 UTC, LEE-GYU-BIN commented on src/main/java/site/sonisori/sonisori/common/DataEntity.java
> +public abstract class DataEntity {
넵 저도 동의해요 수정하겠습니다!

2024-10-21 11:26 UTC, LEE-GYU-BIN commented on src/main/java/site/sonisori/sonisori/entity/SignQuiz.java
> +	@Column(name = "senetece")
감사합니다.. 허점이 많네요

2024-10-21 11:27 UTC, LEE-GYU-BIN commented on src/main/java/site/sonisori/sonisori/entity/User.java
> +	private List<QuizHistory> userHistories;
아 그것도 그렇네요 추가로 세분화 할 필요가 딱히 없어보이네요 좋습니다!

2024-10-22 02:51 UTC, hanbirang approved these changes
코드 확인했습니다! 수고하셨습니다 👍👍
제가 올린 CI PR이 전체적으로 코드 테스트를 해주는 PR이라서 제 PR이 먼저 머지 되는 것이 좋을 것 같아요! PR 확인해주시고 제 꺼 머지되면 머지해주세요

2024-10-22 06:26 UTC, merged